spring.application.name=demo

# Railway MySQL DB
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:39596/railway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=wDWDIWKStvweTjuHQPUwQCfEbPRdsknQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jackson.serialization.fail-on-empty-beans=false

server.port=8080

# ? ?? ?? ?? (HTTPS ?? ??)
# ?? ???? (30?)
server.servlet.session.timeout=30m

# ?? ?? ?? - HTTPS? HTTP ???? ?????
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.max-age=1800
server.servlet.session.cookie.path=/

# ?? ?? ?? ??
server.servlet.session.tracking-modes=cookie

logging.level.com.example.demo=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ????? API ????
api.public-data.service-key=ZNCVPk4K5AlBcu2prllK%2FynRrMIKKv2PuTKoQv7FoxbzV87O5z5C0AQGnnZVZGsObqtxyzRig%2BjrTVsMFij8Hw%3D%3D
recruitment.api.default-rows=20

# Thymeleaf ??
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ?? ??? ?? (PDF ?? ?? ??)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ??? SMTP ?? ?? (??? ???)
spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=nagundo@naver.com
spring.mail.password=KU9QDNPH7LX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT ?? ??
jwt.secret=mySecretKey12345678901234567890123456789012345678901234567890
jwt.expiration=86400000